apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-privileged-container
  annotations:
    configmanagement.gke.io/namespace-selector: test-env
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
